### ISSUE TITLE
Preserve git refspec to local patches and branches after renamed origin's master

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/announcements#179]
For all those who can't pull `master`, it should have renamed to `main`.

To preserve refspec to patches and branches, just changing the `heads/master` to `heads/main` should work.

```diff
[remote "origin"]
	url = https://github.com/dotnet/your-repo
-	fetch = +refs/heads/master:refs/remotes/origin/master
+	fetch = +refs/heads/main:refs/remotes/origin/master
	tagopt = --no-tags
[branch "master"]
	remote = origin
-	merge = refs/heads/master
+	merge = refs/heads/main
```

> Putting this out there, if anyone else facing similar issue with git.

**Comment by Nirmal4G** [comment]
For those who **cannot** change the default branch for _obvious_ 😉 reasons.

**Comment by Nirmal4G** [comment]
Follow-up on #172.

Please do change your local `master` to `main` when you can but for those who can't do it immediately (_like myself_), this should give you more time to do it properly.

**Comment by Trojaner** [comment]
Good job ignoring the readme and what this repo is for.

![image](https://user-images.githubusercontent.com/1809172/111918702-74d8eb80-8a97-11eb-9c02-ba05c583aedb.png)
