### ISSUE TITLE
Needs clarity on open / close source nature of product being announced

### ISSUE THREAD

**Issue by kasper3** [dotnet/announcements#55]
On first page of this repository, it reads:

> Subscribe to this repo to be notified of Announcements and changes in .NET Core.

Does that mean all announcements are related to .NET Core and all products being announced are are open sourced?

If there are announcements about the propitiatory or closed-source products, the products whose sources <b>in full*</b> are not accessible by public, should be marked as such either using a label (https://github.com/dotnet/announcements/labels), or clearly stated in text.

#### * Source code including the build script that generates the package end user downloads from nuget or myget feeds

One example is https://github.com/dotnet/announcements/issues/30, where it is presented to user as if the product ILLink is in open, but the package https://dotnet.myget.org/feed/dotnet-core/package/nuget/Illink.Tasks is produced by script which are nowhere to b found in open. Read more at https://github.com/dotnet/core/issues/915#issuecomment-364645429

**Comment by TAGC** [comment]
> This repo is for team announcements only. To file a bug or start a discussion, please find the appropriate repo in dotnet and create a new issue. For general issue discussions please go to dotnet/core and create a new issue.
