### ISSUE TITLE
Can you help with this issue?

### ISSUE THREAD

**Issue by rudeGit** [dotnet/announcements#56]
https://stackoverflow.com/questions/48819198/weird-behavior-of-httpclienthandler-sslprotocol-property-in-net-framework-4-7-1

**Comment by terrajobst** [comment]
This repo is [only for announcements](https://github.com/dotnet/announcements/blob/master/README.md), not for asking for help. Please file issues in the appropriate repo, which in your case would have been [dotnet/corefx](https://github.com/dotnet/corefx). . I don't mean to be rude by locking this thread but many of our subscribers consider noise like this issue to be uhm... rude too 😄
