### ISSUE TITLE
.net core Console

### ISSUE THREAD

**Issue by bilalMlaik** [dotnet/announcements#92]
I am running dot net core console app as web jobs and it is working perfectly in docker with docker compose. Now the issue is I want to pass a value to the application via Console.ReadLine() over this value i make some decision but i am unable to pass value via Console.ReadLine(). How i can do it please help me. For more understanding, i have added my docker compose file below
`version: '3.4'

services:
  
  tt.core.web:
    image: ${DOCKER_REGISTRY-}ttcoreweb
    build:
      context: .
      dockerfile: TT.Core.Web/Dockerfile
    depends_on:
     - db
    networks:
     - app-network

  tt.core.downtime.webjob:
    image: ${DOCKER_REGISTRY-}ttcoredowntimewebjob
    environment:
      CORE_ENVIRONMENT: devdocker
    build:
      context: .
      dockerfile: TT.Core.Downtime.Webjob/Dockerfile
    depends_on:
     - db
     - tt.core.web
    networks:
     - app-network

  db:
    image: microsoft/mssql-server-linux
    container_name: db
    environment:
      SA_PASSWORD: "Thingtrax%1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "7002:1433"
    networks:
      app-network:
        ipv4_address: 172.24.0.2

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16

`
If the detail is not enough or you do not get my point, you can share your confusion in comment

**Comment by ptMuta** [comment]
Nice password. Now go to StackOverflow or equivalent, this repo is not meant for this.

**Comment by bilalMlaik** [comment]
Alright
